version: '3.0'

services:
  db: 
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - custom

networks:
  custom:
    driver: bridge