name: Main CI

on: [push]

jobs:
    run_tests:
        runs-on: ubuntu-latest
        environment: tests
        env:
            MAIN_URL: ${{ vars.MAIN_URL }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Python 3.10.11
              uses: actions/setup-python@v3
              with:
                  python-version: 3.10.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

            - name: Install Poetry
              run: |
                  pip install poetry
            
            - name: Install Project
              run: |
                  poetry install

            - name: Run tests
              run: |
                  poetry run pytest

            - name: Run mypy
              run: |
                  poetry run mypy ./

            - name: Run pylint
              run: |
                  poetry run pylint ./fast_api

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [run_tests]

    steps:
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . -t ${{ vars.DOCKER_PROJECT }}:${GITHUB_REF_NAME} -f Dockerfile .
      
    - name: Push image to Docker Hub
      run: docker push ${{ vars.DOCKER_PROJECT }}:${GITHUB_REF_NAME}